import {
  ActivityHeart,
  Activity,
  Airplay,
  Airpods,
  AlarmClockCheck,
  AlarmClockMinus,
  AlarmClockOff,
  AlarmClockPlus,
  AlarmClock,
  AlertCircle,
  AlertHexagon,
  AlertOctagon,
  AlertSquare,
  AlertTriangle,
  AlignBottom01,
  AlignBottom02,
  AlignCenter,
  AlignHorizontalCentre01,
  AlignHorizontalCentre02,
  AlignJustify,
  AlignLeft01,
  AlignLeft02,
  AlignLeft,
  AlignRight01,
  AlignRight02,
  AlignRight,
  AlignTopArrow01,
  AlignTopArrow02,
  AlignVerticalCenter01,
  AlignVerticalCenter02,
  Anchor,
  AnnotationAlert,
  AnnotationCheck,
  AnnotationDots,
  AnnotationHeart,
  AnnotationInfo,
  AnnotationPlus,
  AnnotationQuestion,
  AnnotationX,
  Annotation,
  Announcement01,
  Announcement02,
  Announcement03,
  Archive,
  ArrowBlockDown,
  ArrowBlockLeft,
  ArrowBlockRight,
  ArrowBlockUp,
  ArrowCircleBrokenDownLeft,
  ArrowCircleBrokenDownRight,
  ArrowCircleBrokenDown,
  ArrowCircleBrokenLeft,
  ArrowCircleBrokenRight,
  ArrowCircleBrokenUpLeft,
  ArrowCircleBrokenUpRight,
  ArrowCircleBrokenUp,
  ArrowCircleDownLeft,
  ArrowCircleDownRight,
  ArrowCircleDown,
  ArrowCircleLeft,
  ArrowCircleRight,
  ArrowCircleUpLeft,
  ArrowCircleUpRight,
  ArrowCircleUp,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowDown,
  ArrowLeft,
  ArrowNarrowDownLeft,
  ArrowNarrowDownRight,
  ArrowNarrowDown,
  ArrowNarrowLeft,
  ArrowNarrowRight,
  ArrowNarrowUpLeft,
  ArrowNarrowUpRight,
  ArrowNarrowUp,
  ArrowRight,
  ArrowSquareDownLeft,
  ArrowSquareDownRight,
  ArrowSquareDown,
  ArrowSquareLeft,
  ArrowSquareRight,
  ArrowSquareUpLeft,
  ArrowSquareUpRight,
  ArrowSquareUp,
  ArrowUpLeft,
  ArrowUpRight,
  ArrowUp,
  ArrowsDown,
  ArrowsLeft,
  ArrowsRight,
  ArrowsTriangle,
  ArrowsUp,
  Asterisk01,
  Asterisk02,
  AtSign,
  Atom01,
  Atom02,
  Attachment01,
  Attachment02,
  Award01,
  Award02,
  Award03,
  Award04,
  Award05,
  Backpack,
  BankNote01,
  BankNote02,
  BankNote03,
  Bank,
  BarChart01,
  BarChart02,
  BarChart03,
  BarChart04,
  BarChart05,
  BarChart06,
  BarChart07,
  BarChart08,
  BarChart09,
  BarChart10,
  BarChart11,
  BarChart12,
  BarChartCircle01,
  BarChartCircle02,
  BarChartCircle03,
  BarChartSquare01,
  BarChartSquare02,
  BarChartSquare03,
  BarChartSquareDown,
  BarChartSquareMinus,
  BarChartSquarePlus,
  BarChartSquareUp,
  BarLineChart,
  BatteryCharging01,
  BatteryCharging02,
  BatteryEmpty,
  BatteryFull,
  BatteryLow,
  BatteryMid,
  Beaker01,
  Beaker02,
  Bell01,
  Bell02,
  Bell03,
  Bell04,
  BellMinus,
  BellOff01,
  BellOff02,
  BellOff03,
  BellPlus,
  BellRinging01,
  BellRinging02,
  BellRinging03,
  BellRinging04,
  BezierCurve01,
  BezierCurve02,
  BezierCurve03,
  BluetoothConnect,
  BluetoothOff,
  BluetoothOn,
  BluetoothSignal,
  Bold01,
  Bold02,
  BoldSquare,
  BookClosed,
  BookOpen01,
  BookOpen02,
  BookmarkAdd,
  BookmarkCheck,
  BookmarkMinus,
  BookmarkX,
  Bookmark,
  Box,
  BracketsCheck,
  BracketsEllipses,
  BracketsMinus,
  BracketsPlus,
  BracketsSlash,
  BracketsX,
  Brackets,
  Briefcase01,
  Briefcase02,
  Browser,
  Brush01,
  Brush02,
  Brush03,
  Building01,
  Building02,
  Building03,
  Building04,
  Building05,
  Building06,
  Building07,
  Building08,
  Bus,
  Calculator,
  CalendarCheck01,
  CalendarCheck02,
  CalendarDate,
  CalendarHeart01,
  CalendarHeart02,
  CalendarMinus01,
  CalendarMinus02,
  CalendarPlus01,
  CalendarPlus02,
  Calendar,
  Camera01,
  Camera02,
  Camera03,
  CameraLens,
  CameraOff,
  CameraPlus,
  Certificate01,
  Certificate02,
  ChartBreakoutCircle,
  ChartBreakoutSquare,
  CheckCircleBroken,
  CheckCircle,
  CheckDone01,
  CheckDone02,
  CheckHeart,
  CheckSquareBroken,
  CheckSquare,
  CheckVerified01,
  CheckVerified02,
  CheckVerified03,
  Check,
  ChevronDownDouble,
  ChevronDown,
  ChevronLeftDouble,
  ChevronLeft,
  ChevronRightDouble,
  ChevronRight,
  ChevronSelectorHorizontal,
  ChevronSelectorVertical,
  ChevronUpDouble,
  ChevronUp,
  ChromeCast,
  CircleCut,
  Circle,
  Clapperboard,
  ClipboardAttachment,
  ClipboardCheck,
  ClipboardDownload,
  ClipboardMinus,
  ClipboardPlus,
  ClipboardX,
  Clipboard,
  ClockCheck,
  ClockFastForward,
  ClockPlus,
  ClockRefresh,
  ClockRewind,
  ClockSnooze,
  ClockStopwatch,
  Clock,
  Cloud01,
  Cloud02,
  Cloud03,
  CloudBlank01,
  CloudBlank02,
  CloudLightning,
  CloudMoon,
  CloudOff,
  CloudRaining01,
  CloudRaining02,
  CloudRaining03,
  CloudRaining04,
  CloudRaining05,
  CloudRaining06,
  CloudSnowing01,
  CloudSnowing02,
  CloudSun01,
  CloudSun02,
  CloudSun03,
  Code01,
  Code02,
  CodeBrowser,
  CodeCircle01,
  CodeCircle02,
  CodeCircle03,
  CodeSnippet01,
  CodeSnippet02,
  CodeSquare01,
  CodeSquare02,
  Codepen,
  Coins01,
  Coins02,
  Coins03,
  Coins04,
  CoinsHand,
  CoinsStacked01,
  CoinsStacked02,
  CoinsStacked03,
  CoinsStacked04,
  CoinsSwap01,
  CoinsSwap02,
  Colors,
  Columns01,
  Columns02,
  Columns03,
  Command,
  Compass01,
  Compass02,
  Compass03,
  Compass,
  Container,
  Contrast01,
  Contrast02,
  Contrast03,
  Copy01,
  Copy02,
  Copy03,
  Copy04,
  Copy05,
  Copy06,
  Copy07,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftDown,
  CornerLeftUp,
  CornerRightDown,
  CornerRightUp,
  CornerUpLeft,
  CornerUpRight,
  CpuChip01,
  CpuChip02,
  CreditCard01,
  CreditCard02,
  CreditCardCheck,
  CreditCardDown,
  CreditCardDownload,
  CreditCardEdit,
  CreditCardLock,
  CreditCardMinus,
  CreditCardPlus,
  CreditCardRefresh,
  CreditCardSearch,
  CreditCardShield,
  CreditCardUp,
  CreditCardUpload,
  CreditCardX,
  Crop01,
  Crop02,
  Cryptocurrency01,
  Cryptocurrency02,
  Cryptocurrency03,
  Cryptocurrency04,
  Cube01,
  Cube02,
  Cube03,
  Cube04,
  CubeOutline,
  CurrencyBitcoinCircle,
  CurrencyBitcoin,
  CurrencyDollarCircle,
  CurrencyDollar,
  CurrencyEthereumCircle,
  CurrencyEthereum,
  CurrencyEuroCircle,
  CurrencyEuro,
  CurrencyPoundCircle,
  CurrencyPound,
  CurrencyRubleCircle,
  CurrencyRuble,
  CurrencyRupeeCircle,
  CurrencyRupee,
  CurrencyYenCircle,
  CurrencyYen,
  Cursor01,
  Cursor02,
  Cursor03,
  Cursor04,
  CursorBox,
  CursorClick01,
  CursorClick02,
  Data,
  Database01,
  Database02,
  Database03,
  Dataflow01,
  Dataflow02,
  Dataflow03,
  Dataflow04,
  Delete,
  Diamond01,
  Diamond02,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Disc01,
  Disc02,
  DistributeSpacingHorizontal,
  DistributeSpacingVertical,
  Divide01,
  Divide02,
  Divide03,
  Divider,
  Dotpoints01,
  Dotpoints02,
  DotsGrid,
  DotsHorizontal,
  DotsVertical,
  Download01,
  Download02,
  Download03,
  Download04,
  DownloadCloud01,
  DownloadCloud02,
  Drop,
  Droplets01,
  Droplets02,
  Droplets03,
  Dropper,
  Edit01,
  Edit02,
  Edit03,
  Edit04,
  Edit05,
  EqualNot,
  Equal,
  Eraser,
  Expand01,
  Expand02,
  Expand03,
  Expand04,
  Expand05,
  Expand06,
  EyeOff,
  Eye,
  FaceContent,
  FaceFrown,
  FaceHappy,
  FaceIdSquare,
  FaceId,
  FaceNeutral,
  FaceSad,
  FaceSmile,
  FaceWink,
  FastBackward,
  FastForward,
  Feather,
  Figma,
  File01,
  File02,
  File03,
  File04,
  File05,
  File06,
  File07,
  FileAttachment01,
  FileAttachment02,
  FileAttachment03,
  FileAttachment04,
  FileAttachment05,
  FileCheck01,
  FileCheck02,
  FileCheck03,
  FileCode01,
  FileCode02,
  FileDownload01,
  FileDownload02,
  FileDownload03,
  FileHeart01,
  FileHeart02,
  FileHeart03,
  FileLock01,
  FileLock02,
  FileLock03,
  FileMinus01,
  FileMinus02,
  FileMinus03,
  FilePlus01,
  FilePlus02,
  FilePlus03,
  FileQuestion01,
  FileQuestion02,
  FileQuestion03,
  FileSearch01,
  FileSearch02,
  FileSearch03,
  FileShield01,
  FileShield02,
  FileShield03,
  FileX01,
  FileX02,
  FileX03,
  Film01,
  Film02,
  Film03,
  FilterFunnel01,
  FilterFunnel02,
  FilterLines,
  Fingerprint01,
  Fingerprint02,
  Fingerprint03,
  Fingerprint04,
  Flag01,
  Flag02,
  Flag03,
  Flag04,
  Flag05,
  Flag06,
  FlashOff,
  Flash,
  FlexAlignBottom,
  FlexAlignLeft,
  FlexAlignRight,
  FlexAlignTop,
  FlipBackward,
  FlipForward,
  FolderCheck,
  FolderClosed,
  FolderCode,
  FolderDownload,
  FolderLock,
  FolderMinus,
  FolderPlus,
  FolderQuestion,
  FolderSearch,
  FolderShield,
  FolderX,
  Folder,
  Framer,
  GamingPad01,
  GamingPad02,
  Gift01,
  Gift02,
  GitBranch01,
  GitBranch02,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Glasses01,
  Glasses02,
  Globe01,
  Globe02,
  Globe03,
  Globe04,
  Globe05,
  Globe06,
  GoogleChrome,
  GraduationHat01,
  GraduationHat02,
  Grid01,
  Grid02,
  Grid03,
  GridDotsBlank,
  GridDotsBottom,
  GridDotsHorizontalCenter,
  GridDotsLeft,
  GridDotsOuter,
  GridDotsRight,
  GridDotsTop,
  GridDotsVerticalCenter,
  Hand,
  HardDrive,
  Hash01,
  Hash02,
  Heading01,
  Heading02,
  HeadingSquare,
  Headphones01,
  Headphones02,
  HeartCircle,
  HeartHand,
  HeartHexagon,
  HeartOctagon,
  HeartRounded,
  HeartSquare,
  Heart,
  Hearts,
  HelpCircle,
  HelpOctagon1,
  HelpOctagon,
  HelpSquare,
  Hexagon01,
  Hexagon02,
  Home01,
  Home02,
  Home03,
  Home04,
  Home05,
  HomeLine,
  HomeSmile,
  HorizontalBarChart01,
  HorizontalBarChart02,
  HorizontalBarChart03,
  Hourglass01,
  Hourglass02,
  Hourglass03,
  Hurricane01,
  Hurricane02,
  Hurricane03,
  Image01,
  Image02,
  Image03,
  Image04,
  Image05,
  ImageCheck,
  ImageDown,
  ImageIndentLeft,
  ImageIndentRight,
  ImageLeft,
  ImagePlus,
  ImageRight,
  ImageUp,
  ImageUserCheck,
  ImageUserDown,
  ImageUserLeft,
  ImageUserPlus,
  ImageUserRight,
  ImageUserUp,
  ImageUserX,
  ImageUser,
  ImageX,
  Inbox01,
  Inbox02,
  Infinity,
  InfoCircle,
  InfoHexagon,
  InfoOctagon,
  InfoSquare,
  IntersectCircle,
  IntersectSquare,
  Italic01,
  Italic02,
  ItalicSquare,
  Key01,
  Key02,
  Keyboard01,
  Keyboard02,
  Laptop01,
  Laptop02,
  LayerSingle,
  LayersThree01,
  LayersThree02,
  LayersTwo01,
  LayersTwo02,
  LayoutAlt01,
  LayoutAlt02,
  LayoutAlt03,
  LayoutAlt04,
  LayoutBottom,
  LayoutGrid01,
  LayoutGrid02,
  LayoutLeft,
  LayoutRight,
  LayoutTop,
  LeftIndent01,
  LeftIndent02,
  LetterSpacing01,
  LetterSpacing02,
  LifeBuoy01,
  LifeBuoy02,
  Lightbulb01,
  Lightbulb02,
  Lightbulb03,
  Lightbulb04,
  Lightbulb05,
  Lightning01,
  Lightning02,
  LineChartDown01,
  LineChartDown02,
  LineChartDown03,
  LineChartDown04,
  LineChartDown05,
  LineChartUp01,
  LineChartUp02,
  LineChartUp03,
  LineChartUp04,
  LineChartUp05,
  LineHeight,
  Link01,
  Link02,
  Link03,
  Link04,
  Link05,
  LinkBroken01,
  LinkBroken02,
  LinkExternal01,
  LinkExternal02,
  List,
  Loading01,
  Loading02,
  Loading03,
  Lock01,
  Lock02,
  Lock03,
  Lock04,
  LockKeyholeCircle,
  LockKeyholeSquare,
  LockUnlocked01,
  LockUnlocked02,
  LockUnlocked03,
  LockUnlocked04,
  LogIn01,
  LogIn02,
  LogIn03,
  LogIn04,
  LogOut01,
  LogOut02,
  LogOut03,
  LogOut04,
  Luggage01,
  Luggage02,
  Luggage03,
  MagicWand01,
  MagicWand02,
  Mail01,
  Mail02,
  Mail03,
  Mail04,
  Mail05,
  Map01,
  Map02,
  Mark,
  MarkerPin01,
  MarkerPin02,
  MarkerPin03,
  MarkerPin04,
  MarkerPin05,
  MarkerPin06,
  Maximize01,
  Maximize02,
  MedicalCircle,
  MedicalCross,
  MedicalSquare,
  Menu01,
  Menu02,
  Menu03,
  Menu04,
  Menu05,
  MessageAlertCircle,
  MessageAlertSquare,
  MessageChatCircle,
  MessageChatSquare,
  MessageCheckCircle,
  MessageCheckSquare,
  MessageCircle01,
  MessageCircle02,
  MessageDotsCircle,
  MessageDotsSquare,
  MessageHeartCircle,
  MessageHeartSquare,
  MessageNotificationCircle,
  MessageNotificationSquare,
  MessagePlusCircle,
  MessagePlusSquare,
  MessageQuestionCircle,
  MessageQuestionSquare,
  MessageSmileCircle,
  MessageSmileSquare,
  MessageSquare01,
  MessageSquare02,
  MessageTextCircle01,
  MessageTextCircle02,
  MessageTextSquare01,
  MessageTextSquare02,
  MessageXCircle,
  MessageXSquare,
  Microphone01,
  Microphone02,
  MicrophoneOff01,
  MicrophoneOff02,
  Microscope,
  Minimize01,
  Minimize02,
  MinusCircle,
  MinusSquare,
  Minus,
  Modem01,
  Modem02,
  Monitor01,
  Monitor02,
  Monitor03,
  Monitor04,
  Monitor05,
  Moon01,
  Moon02,
  MoonEclipse,
  MoonStar,
  Mouse,
  Move,
  MusicNote01,
  MusicNote02,
  MusicNotePlus,
  NavigationPointer01,
  NavigationPointer02,
  NavigationPointerOff01,
  NavigationPointerOff02,
  NotificationBox,
  NotificationMessage,
  NotificationText,
  Octagon,
  PackageCheck,
  PackageMinus,
  PackagePlus,
  PackageSearch,
  PackageX,
  Package,
  PaintPour,
  Paint,
  Palette,
  Paperclip,
  ParagraphSpacing,
  ParagraphWrap,
  PasscodeLock,
  Passcode,
  Passport,
  PauseCircle,
  PauseSquare,
  PenTool01,
  PenTool02,
  PenToolMinus,
  PenToolPlus,
  Pencil01,
  Pencil02,
  PencilLine,
  Pentagon,
  Percent01,
  Percent02,
  Percent03,
  Perspective01,
  Perspective02,
  Phone01,
  Phone02,
  PhoneCall01,
  PhoneCall02,
  PhoneHangUp,
  PhoneIncoming01,
  PhoneIncoming02,
  PhoneOutgoing01,
  PhoneOutgoing02,
  PhonePause,
  PhonePlus,
  PhoneX,
  Phone,
  PieChart01,
  PieChart02,
  PieChart03,
  PieChart04,
  PiggyBank01,
  PiggyBank02,
  Pilcrow01,
  Pilcrow02,
  PilcrowSquare,
  Pin01,
  Pin02,
  Placeholder,
  Plane,
  PlayCircle,
  PlaySquare,
  Play,
  PlusCircle,
  PlusSquare,
  Plus,
  Podcast,
  Power01,
  Power02,
  Power03,
  PresentationChart01,
  PresentationChart02,
  PresentationChart03,
  Printer,
  PuzzlePiece01,
  PuzzlePiece02,
  QrCode01,
  QrCode02,
  ReceiptCheck,
  Receipt,
  Recording01,
  Recording02,
  Recording03,
  Reflect01,
  Reflect02,
  RefreshCcw01,
  RefreshCcw02,
  RefreshCcw03,
  RefreshCcw04,
  RefreshCcw05,
  RefreshCw01,
  RefreshCw02,
  RefreshCw03,
  RefreshCw04,
  RefreshCw05,
  Repeat01,
  Repeat02,
  Repeat03,
  Repeat04,
  ReverseLeft,
  ReverseRight,
  RightIndent01,
  RightIndent02,
  Rocket01,
  Rocket02,
  RollerBrush,
  Route,
  Rows01,
  Rows02,
  Rows03,
  Rss01,
  Rss02,
  Ruler,
  Safe,
  Sale01,
  Sale02,
  Sale03,
  Sale04,
  Save01,
  Save02,
  Save03,
  Scale01,
  Scale02,
  Scale03,
  Scales01,
  Scales02,
  Scan,
  Scissors01,
  Scissors02,
  ScissorsCut01,
  ScissorsCut02,
  SearchLg,
  SearchMd,
  SearchRefraction,
  SearchSm,
  Send01,
  Send02,
  Send03,
  Server01,
  Server02,
  Server03,
  Server04,
  Server05,
  Server06,
  Settings01,
  Settings02,
  Settings03,
  Settings04,
  Share01,
  Share02,
  Share03,
  Share04,
  Share05,
  Share06,
  Share07,
  Shield01,
  Shield02,
  Shield03,
  ShieldDollar,
  ShieldOff,
  ShieldPlus,
  ShieldTick,
  ShieldZap,
  ShoppingBag01,
  ShoppingBag02,
  ShoppingBag03,
  ShoppingCart01,
  ShoppingCart02,
  ShoppingCart03,
  Shuffle01,
  Shuffle02,
  Signal01,
  Signal02,
  Signal03,
  Simcard,
  Skew,
  SkipBack,
  SkipForward,
  SlashCircle01,
  SlashCircle02,
  SlashDivider,
  SlashOctagon,
  Sliders01,
  Sliders02,
  Sliders03,
  Sliders04,
  Snowflake01,
  Snowflake02,
  SpacingHeight01,
  SpacingHeight02,
  SpacingWidth01,
  SpacingWidth02,
  Speaker01,
  Speaker02,
  Speaker03,
  Speedometer01,
  Speedometer02,
  Speedometer03,
  Speedometer04,
  Square,
  Stand,
  Star01,
  Star02,
  Star03,
  Star04,
  Star05,
  Star06,
  Star07,
  Stars01,
  Stars02,
  Stars03,
  StickerCircle,
  StickerSquare,
  StopCircle,
  StopSquare,
  Stop,
  Strikethrough01,
  Strikethrough02,
  StrikethroughSquare,
  Subscript,
  SunSetting01,
  SunSetting02,
  SunSetting03,
  Sun,
  Sunrise,
  Sunset,
  SwitchHorizontal01,
  SwitchHorizontal02,
  SwitchVertical01,
  SwitchVertical02,
  Table,
  Tablet01,
  Tablet02,
  Tag01,
  Tag02,
  Tag03,
  Target01,
  Target02,
  Target03,
  Target04,
  Target05,
  Telescope,
  TerminalBrowser,
  TerminalCircle,
  TerminalSquare,
  Terminal,
  TextInput,
  Thermometer01,
  Thermometer02,
  Thermometer03,
  ThermometerCold,
  ThermometerWarm,
  ThumbsDown,
  ThumbsUp,
  Ticket01,
  Ticket02,
  Toggle01Left,
  Toggle01Right,
  Toggle02Left,
  Toggle02Right,
  Toggle03Left,
  Toggle03Right,
  Tool01,
  Tool02,
  Train,
  Tram,
  Transform,
  Translate01,
  Translate02,
  Trash01,
  Trash02,
  Trash03,
  Trash04,
  TrendDown01,
  TrendDown02,
  TrendUp01,
  TrendUp02,
  Triangle,
  Trophy01,
  Trophy02,
  Truck01,
  Truck02,
  Tv01,
  Tv02,
  Tv03,
  Type01,
  Type02,
  TypeSquare,
  TypeStrikethrough01,
  TypeStrikethrough02,
  Umbrella01,
  Umbrella02,
  Umbrella03,
  Underline01,
  Underline02,
  UnderlineSquare,
  Upload01,
  Upload02,
  Upload03,
  Upload04,
  UploadCloud01,
  UploadCloud02,
  UsbFlashDrive,
  User01,
  User02,
  User03,
  UserCheck01,
  UserCheck02,
  UserCircle,
  UserDown01,
  UserDown02,
  UserEdit,
  UserLeft01,
  UserLeft02,
  UserMinus01,
  UserMinus02,
  UserPlus01,
  UserPlus02,
  UserRight01,
  UserRight02,
  UserSquare,
  UserUp01,
  UserUp02,
  UserX01,
  UserX02,
  Users01,
  Users02,
  Users03,
  UsersCheck,
  UsersDown,
  UsersEdit,
  UsersLeft,
  UsersMinus,
  UsersPlus,
  UsersRight,
  UsersUp,
  UsersX,
  Variable,
  VideoRecorderOff,
  VideoRecorder,
  Virus,
  Voicemail,
  VolumeMax,
  VolumeMin,
  VolumeMinus,
  VolumePlus,
  VolumeX,
  Wallet01,
  Wallet02,
  Wallet03,
  Wallet04,
  Wallet05,
  WatchCircle,
  WatchSquare,
  Waves,
  Webcam01,
  Webcam02,
  WifiOff,
  Wifi,
  Wind01,
  Wind02,
  Wind03,
  XCircle,
  XClose,
  XSquare,
  X,
  Youtube,
  ZapCircle,
  ZapFast,
  ZapOff,
  ZapSquare,
  Zap,
  ZoomIn,
  ZoomOut,
} from '../../../../assets/icons';

export const iconMap = {
  'activity-heart': ActivityHeart,
  activity: Activity,
  airplay: Airplay,
  airpods: Airpods,
  'alarm-clock-check': AlarmClockCheck,
  'alarm-clock-minus': AlarmClockMinus,
  'alarm-clock-off': AlarmClockOff,
  'alarm-clock-plus': AlarmClockPlus,
  'alarm-clock': AlarmClock,
  'alert-circle': AlertCircle,
  'alert-hexagon': AlertHexagon,
  'alert-octagon': AlertOctagon,
  'alert-square': AlertSquare,
  'alert-triangle': AlertTriangle,
  'align-bottom-01': AlignBottom01,
  'align-bottom-02': AlignBottom02,
  'align-center': AlignCenter,
  'align-horizontal-centre-01': AlignHorizontalCentre01,
  'align-horizontal-centre-02': AlignHorizontalCentre02,
  'align-justify': AlignJustify,
  'align-left-01': AlignLeft01,
  'align-left-02': AlignLeft02,
  'align-left': AlignLeft,
  'align-right-01': AlignRight01,
  'align-right-02': AlignRight02,
  'align-right': AlignRight,
  'align-top-arrow-01': AlignTopArrow01,
  'align-top-arrow-02': AlignTopArrow02,
  'align-vertical-center-01': AlignVerticalCenter01,
  'align-vertical-center-02': AlignVerticalCenter02,
  anchor: Anchor,
  'annotation-alert': AnnotationAlert,
  'annotation-check': AnnotationCheck,
  'annotation-dots': AnnotationDots,
  'annotation-heart': AnnotationHeart,
  'annotation-info': AnnotationInfo,
  'annotation-plus': AnnotationPlus,
  'annotation-question': AnnotationQuestion,
  'annotation-x': AnnotationX,
  annotation: Annotation,
  'announcement-01': Announcement01,
  'announcement-02': Announcement02,
  'announcement-03': Announcement03,
  archive: Archive,
  'arrow-block-down': ArrowBlockDown,
  'arrow-block-left': ArrowBlockLeft,
  'arrow-block-right': ArrowBlockRight,
  'arrow-block-up': ArrowBlockUp,
  'arrow-circle-broken-down-left': ArrowCircleBrokenDownLeft,
  'arrow-circle-broken-down-right': ArrowCircleBrokenDownRight,
  'arrow-circle-broken-down': ArrowCircleBrokenDown,
  'arrow-circle-broken-left': ArrowCircleBrokenLeft,
  'arrow-circle-broken-right': ArrowCircleBrokenRight,
  'arrow-circle-broken-up-left': ArrowCircleBrokenUpLeft,
  'arrow-circle-broken-up-right': ArrowCircleBrokenUpRight,
  'arrow-circle-broken-up': ArrowCircleBrokenUp,
  'arrow-circle-down-left': ArrowCircleDownLeft,
  'arrow-circle-down-right': ArrowCircleDownRight,
  'arrow-circle-down': ArrowCircleDown,
  'arrow-circle-left': ArrowCircleLeft,
  'arrow-circle-right': ArrowCircleRight,
  'arrow-circle-up-left': ArrowCircleUpLeft,
  'arrow-circle-up-right': ArrowCircleUpRight,
  'arrow-circle-up': ArrowCircleUp,
  'arrow-down-left': ArrowDownLeft,
  'arrow-down-right': ArrowDownRight,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-narrow-down-left': ArrowNarrowDownLeft,
  'arrow-narrow-down-right': ArrowNarrowDownRight,
  'arrow-narrow-down': ArrowNarrowDown,
  'arrow-narrow-left': ArrowNarrowLeft,
  'arrow-narrow-right': ArrowNarrowRight,
  'arrow-narrow-up-left': ArrowNarrowUpLeft,
  'arrow-narrow-up-right': ArrowNarrowUpRight,
  'arrow-narrow-up': ArrowNarrowUp,
  'arrow-right': ArrowRight,
  'arrow-square-down-left': ArrowSquareDownLeft,
  'arrow-square-down-right': ArrowSquareDownRight,
  'arrow-square-down': ArrowSquareDown,
  'arrow-square-left': ArrowSquareLeft,
  'arrow-square-right': ArrowSquareRight,
  'arrow-square-up-left': ArrowSquareUpLeft,
  'arrow-square-up-right': ArrowSquareUpRight,
  'arrow-square-up': ArrowSquareUp,
  'arrow-up-left': ArrowUpLeft,
  'arrow-up-right': ArrowUpRight,
  'arrow-up': ArrowUp,
  'arrows-down': ArrowsDown,
  'arrows-left': ArrowsLeft,
  'arrows-right': ArrowsRight,
  'arrows-triangle': ArrowsTriangle,
  'arrows-up': ArrowsUp,
  'asterisk-01': Asterisk01,
  'asterisk-02': Asterisk02,
  'at-sign': AtSign,
  'atom-01': Atom01,
  'atom-02': Atom02,
  'attachment-01': Attachment01,
  'attachment-02': Attachment02,
  'award-01': Award01,
  'award-02': Award02,
  'award-03': Award03,
  'award-04': Award04,
  'award-05': Award05,
  backpack: Backpack,
  'bank-note-01': BankNote01,
  'bank-note-02': BankNote02,
  'bank-note-03': BankNote03,
  bank: Bank,
  'bar-chart-01': BarChart01,
  'bar-chart-02': BarChart02,
  'bar-chart-03': BarChart03,
  'bar-chart-04': BarChart04,
  'bar-chart-05': BarChart05,
  'bar-chart-06': BarChart06,
  'bar-chart-07': BarChart07,
  'bar-chart-08': BarChart08,
  'bar-chart-09': BarChart09,
  'bar-chart-10': BarChart10,
  'bar-chart-11': BarChart11,
  'bar-chart-12': BarChart12,
  'bar-chart-circle-01': BarChartCircle01,
  'bar-chart-circle-02': BarChartCircle02,
  'bar-chart-circle-03': BarChartCircle03,
  'bar-chart-square-01': BarChartSquare01,
  'bar-chart-square-02': BarChartSquare02,
  'bar-chart-square-03': BarChartSquare03,
  'bar-chart-square-down': BarChartSquareDown,
  'bar-chart-square-minus': BarChartSquareMinus,
  'bar-chart-square-plus': BarChartSquarePlus,
  'bar-chart-square-up': BarChartSquareUp,
  'bar-line-chart': BarLineChart,
  'battery-charging-01': BatteryCharging01,
  'battery-charging-02': BatteryCharging02,
  'battery-empty': BatteryEmpty,
  'battery-full': BatteryFull,
  'battery-low': BatteryLow,
  'battery-mid': BatteryMid,
  'beaker-01': Beaker01,
  'beaker-02': Beaker02,
  'bell-01': Bell01,
  'bell-02': Bell02,
  'bell-03': Bell03,
  'bell-04': Bell04,
  'bell-minus': BellMinus,
  'bell-off-01': BellOff01,
  'bell-off-02': BellOff02,
  'bell-off-03': BellOff03,
  'bell-plus': BellPlus,
  'bell-ringing-01': BellRinging01,
  'bell-ringing-02': BellRinging02,
  'bell-ringing-03': BellRinging03,
  'bell-ringing-04': BellRinging04,
  'bezier-curve-01': BezierCurve01,
  'bezier-curve-02': BezierCurve02,
  'bezier-curve-03': BezierCurve03,
  'bluetooth-connect': BluetoothConnect,
  'bluetooth-off': BluetoothOff,
  'bluetooth-on': BluetoothOn,
  'bluetooth-signal': BluetoothSignal,
  'bold-01': Bold01,
  'bold-02': Bold02,
  'bold-square': BoldSquare,
  'book-closed': BookClosed,
  'book-open-01': BookOpen01,
  'book-open-02': BookOpen02,
  'bookmark-add': BookmarkAdd,
  'bookmark-check': BookmarkCheck,
  'bookmark-minus': BookmarkMinus,
  'bookmark-x': BookmarkX,
  bookmark: Bookmark,
  box: Box,
  'brackets-check': BracketsCheck,
  'brackets-ellipses': BracketsEllipses,
  'brackets-minus': BracketsMinus,
  'brackets-plus': BracketsPlus,
  'brackets-slash': BracketsSlash,
  'brackets-x': BracketsX,
  brackets: Brackets,
  'briefcase-01': Briefcase01,
  'briefcase-02': Briefcase02,
  browser: Browser,
  'brush-01': Brush01,
  'brush-02': Brush02,
  'brush-03': Brush03,
  'building-01': Building01,
  'building-02': Building02,
  'building-03': Building03,
  'building-04': Building04,
  'building-05': Building05,
  'building-06': Building06,
  'building-07': Building07,
  'building-08': Building08,
  bus: Bus,
  calculator: Calculator,
  'calendar-check-01': CalendarCheck01,
  'calendar-check-02': CalendarCheck02,
  'calendar-date': CalendarDate,
  'calendar-heart-01': CalendarHeart01,
  'calendar-heart-02': CalendarHeart02,
  'calendar-minus-01': CalendarMinus01,
  'calendar-minus-02': CalendarMinus02,
  'calendar-plus-01': CalendarPlus01,
  'calendar-plus-02': CalendarPlus02,
  calendar: Calendar,
  'camera-01': Camera01,
  'camera-02': Camera02,
  'camera-03': Camera03,
  'camera-lens': CameraLens,
  'camera-off': CameraOff,
  'camera-plus': CameraPlus,
  'certificate-01': Certificate01,
  'certificate-02': Certificate02,
  'chart-breakout-circle': ChartBreakoutCircle,
  'chart-breakout-square': ChartBreakoutSquare,
  'check-circle-broken': CheckCircleBroken,
  'check-circle': CheckCircle,
  'check-done-01': CheckDone01,
  'check-done-02': CheckDone02,
  'check-heart': CheckHeart,
  'check-square-broken': CheckSquareBroken,
  'check-square': CheckSquare,
  'check-verified-01': CheckVerified01,
  'check-verified-02': CheckVerified02,
  'check-verified-03': CheckVerified03,
  check: Check,
  'chevron-down-double': ChevronDownDouble,
  'chevron-down': ChevronDown,
  'chevron-left-double': ChevronLeftDouble,
  'chevron-left': ChevronLeft,
  'chevron-right-double': ChevronRightDouble,
  'chevron-right': ChevronRight,
  'chevron-selector-horizontal': ChevronSelectorHorizontal,
  'chevron-selector-vertical': ChevronSelectorVertical,
  'chevron-up-double': ChevronUpDouble,
  'chevron-up': ChevronUp,
  'chrome-cast': ChromeCast,
  'circle-cut': CircleCut,
  circle: Circle,
  clapperboard: Clapperboard,
  'clipboard-attachment': ClipboardAttachment,
  'clipboard-check': ClipboardCheck,
  'clipboard-download': ClipboardDownload,
  'clipboard-minus': ClipboardMinus,
  'clipboard-plus': ClipboardPlus,
  'clipboard-x': ClipboardX,
  clipboard: Clipboard,
  'clock-check': ClockCheck,
  'clock-fast-forward': ClockFastForward,
  'clock-plus': ClockPlus,
  'clock-refresh': ClockRefresh,
  'clock-rewind': ClockRewind,
  'clock-snooze': ClockSnooze,
  'clock-stopwatch': ClockStopwatch,
  clock: Clock,
  'cloud-01': Cloud01,
  'cloud-02': Cloud02,
  'cloud-03': Cloud03,
  'cloud-blank-01': CloudBlank01,
  'cloud-blank-02': CloudBlank02,
  'cloud-lightning': CloudLightning,
  'cloud-moon': CloudMoon,
  'cloud-off': CloudOff,
  'cloud-raining-01': CloudRaining01,
  'cloud-raining-02': CloudRaining02,
  'cloud-raining-03': CloudRaining03,
  'cloud-raining-04': CloudRaining04,
  'cloud-raining-05': CloudRaining05,
  'cloud-raining-06': CloudRaining06,
  'cloud-snowing-01': CloudSnowing01,
  'cloud-snowing-02': CloudSnowing02,
  'cloud-sun-01': CloudSun01,
  'cloud-sun-02': CloudSun02,
  'cloud-sun-03': CloudSun03,
  'code-01': Code01,
  'code-02': Code02,
  'code-browser': CodeBrowser,
  'code-circle-01': CodeCircle01,
  'code-circle-02': CodeCircle02,
  'code-circle-03': CodeCircle03,
  'code-snippet-01': CodeSnippet01,
  'code-snippet-02': CodeSnippet02,
  'code-square-01': CodeSquare01,
  'code-square-02': CodeSquare02,
  codepen: Codepen,
  'coins-01': Coins01,
  'coins-02': Coins02,
  'coins-03': Coins03,
  'coins-04': Coins04,
  'coins-hand': CoinsHand,
  'coins-stacked-01': CoinsStacked01,
  'coins-stacked-02': CoinsStacked02,
  'coins-stacked-03': CoinsStacked03,
  'coins-stacked-04': CoinsStacked04,
  'coins-swap-01': CoinsSwap01,
  'coins-swap-02': CoinsSwap02,
  colors: Colors,
  'columns-01': Columns01,
  'columns-02': Columns02,
  'columns-03': Columns03,
  command: Command,
  'compass-01': Compass01,
  'compass-02': Compass02,
  'compass-03': Compass03,
  compass: Compass,
  container: Container,
  'contrast-01': Contrast01,
  'contrast-02': Contrast02,
  'contrast-03': Contrast03,
  'copy-01': Copy01,
  'copy-02': Copy02,
  'copy-03': Copy03,
  'copy-04': Copy04,
  'copy-05': Copy05,
  'copy-06': Copy06,
  'copy-07': Copy07,
  'corner-down-left': CornerDownLeft,
  'corner-down-right': CornerDownRight,
  'corner-left-down': CornerLeftDown,
  'corner-left-up': CornerLeftUp,
  'corner-right-down': CornerRightDown,
  'corner-right-up': CornerRightUp,
  'corner-up-left': CornerUpLeft,
  'corner-up-right': CornerUpRight,
  'cpu-chip-01': CpuChip01,
  'cpu-chip-02': CpuChip02,
  'credit-card-01': CreditCard01,
  'credit-card-02': CreditCard02,
  'credit-card-check': CreditCardCheck,
  'credit-card-down': CreditCardDown,
  'credit-card-download': CreditCardDownload,
  'credit-card-edit': CreditCardEdit,
  'credit-card-lock': CreditCardLock,
  'credit-card-minus': CreditCardMinus,
  'credit-card-plus': CreditCardPlus,
  'credit-card-refresh': CreditCardRefresh,
  'credit-card-search': CreditCardSearch,
  'credit-card-shield': CreditCardShield,
  'credit-card-up': CreditCardUp,
  'credit-card-upload': CreditCardUpload,
  'credit-card-x': CreditCardX,
  'crop-01': Crop01,
  'crop-02': Crop02,
  'cryptocurrency-01': Cryptocurrency01,
  'cryptocurrency-02': Cryptocurrency02,
  'cryptocurrency-03': Cryptocurrency03,
  'cryptocurrency-04': Cryptocurrency04,
  'cube-01': Cube01,
  'cube-02': Cube02,
  'cube-03': Cube03,
  'cube-04': Cube04,
  'cube-outline': CubeOutline,
  'currency-bitcoin-circle': CurrencyBitcoinCircle,
  'currency-bitcoin': CurrencyBitcoin,
  'currency-dollar-circle': CurrencyDollarCircle,
  'currency-dollar': CurrencyDollar,
  'currency-ethereum-circle': CurrencyEthereumCircle,
  'currency-ethereum': CurrencyEthereum,
  'currency-euro-circle': CurrencyEuroCircle,
  'currency-euro': CurrencyEuro,
  'currency-pound-circle': CurrencyPoundCircle,
  'currency-pound': CurrencyPound,
  'currency-ruble-circle': CurrencyRubleCircle,
  'currency-ruble': CurrencyRuble,
  'currency-rupee-circle': CurrencyRupeeCircle,
  'currency-rupee': CurrencyRupee,
  'currency-yen-circle': CurrencyYenCircle,
  'currency-yen': CurrencyYen,
  'cursor-01': Cursor01,
  'cursor-02': Cursor02,
  'cursor-03': Cursor03,
  'cursor-04': Cursor04,
  'cursor-box': CursorBox,
  'cursor-click-01': CursorClick01,
  'cursor-click-02': CursorClick02,
  data: Data,
  'database-01': Database01,
  'database-02': Database02,
  'database-03': Database03,
  'dataflow-01': Dataflow01,
  'dataflow-02': Dataflow02,
  'dataflow-03': Dataflow03,
  'dataflow-04': Dataflow04,
  delete: Delete,
  'diamond-01': Diamond01,
  'diamond-02': Diamond02,
  'dice-1': Dice1,
  'dice-2': Dice2,
  'dice-3': Dice3,
  'dice-4': Dice4,
  'dice-5': Dice5,
  'dice-6': Dice6,
  'disc-01': Disc01,
  'disc-02': Disc02,
  'distribute-spacing-horizontal': DistributeSpacingHorizontal,
  'distribute-spacing-vertical': DistributeSpacingVertical,
  'divide-01': Divide01,
  'divide-02': Divide02,
  'divide-03': Divide03,
  divider: Divider,
  'dotpoints-01': Dotpoints01,
  'dotpoints-02': Dotpoints02,
  'dots-grid': DotsGrid,
  'dots-horizontal': DotsHorizontal,
  'dots-vertical': DotsVertical,
  'download-01': Download01,
  'download-02': Download02,
  'download-03': Download03,
  'download-04': Download04,
  'download-cloud-01': DownloadCloud01,
  'download-cloud-02': DownloadCloud02,
  drop: Drop,
  'droplets-01': Droplets01,
  'droplets-02': Droplets02,
  'droplets-03': Droplets03,
  dropper: Dropper,
  'edit-01': Edit01,
  'edit-02': Edit02,
  'edit-03': Edit03,
  'edit-04': Edit04,
  'edit-05': Edit05,
  'equal-not': EqualNot,
  equal: Equal,
  eraser: Eraser,
  'expand-01': Expand01,
  'expand-02': Expand02,
  'expand-03': Expand03,
  'expand-04': Expand04,
  'expand-05': Expand05,
  'expand-06': Expand06,
  'eye-off': EyeOff,
  eye: Eye,
  'face-content': FaceContent,
  'face-frown': FaceFrown,
  'face-happy': FaceHappy,
  'face-id-square': FaceIdSquare,
  'face-id': FaceId,
  'face-neutral': FaceNeutral,
  'face-sad': FaceSad,
  'face-smile': FaceSmile,
  'face-wink': FaceWink,
  'fast-backward': FastBackward,
  'fast-forward': FastForward,
  feather: Feather,
  figma: Figma,
  'file-01': File01,
  'file-02': File02,
  'file-03': File03,
  'file-04': File04,
  'file-05': File05,
  'file-06': File06,
  'file-07': File07,
  'file-attachment-01': FileAttachment01,
  'file-attachment-02': FileAttachment02,
  'file-attachment-03': FileAttachment03,
  'file-attachment-04': FileAttachment04,
  'file-attachment-05': FileAttachment05,
  'file-check-01': FileCheck01,
  'file-check-02': FileCheck02,
  'file-check-03': FileCheck03,
  'file-code-01': FileCode01,
  'file-code-02': FileCode02,
  'file-download-01': FileDownload01,
  'file-download-02': FileDownload02,
  'file-download-03': FileDownload03,
  'file-heart-01': FileHeart01,
  'file-heart-02': FileHeart02,
  'file-heart-03': FileHeart03,
  'file-lock-01': FileLock01,
  'file-lock-02': FileLock02,
  'file-lock-03': FileLock03,
  'file-minus-01': FileMinus01,
  'file-minus-02': FileMinus02,
  'file-minus-03': FileMinus03,
  'file-plus-01': FilePlus01,
  'file-plus-02': FilePlus02,
  'file-plus-03': FilePlus03,
  'file-question-01': FileQuestion01,
  'file-question-02': FileQuestion02,
  'file-question-03': FileQuestion03,
  'file-search-01': FileSearch01,
  'file-search-02': FileSearch02,
  'file-search-03': FileSearch03,
  'file-shield-01': FileShield01,
  'file-shield-02': FileShield02,
  'file-shield-03': FileShield03,
  'file-x-01': FileX01,
  'file-x-02': FileX02,
  'file-x-03': FileX03,
  'film-01': Film01,
  'film-02': Film02,
  'film-03': Film03,
  'filter-funnel-01': FilterFunnel01,
  'filter-funnel-02': FilterFunnel02,
  'filter-lines': FilterLines,
  'fingerprint-01': Fingerprint01,
  'fingerprint-02': Fingerprint02,
  'fingerprint-03': Fingerprint03,
  'fingerprint-04': Fingerprint04,
  'flag-01': Flag01,
  'flag-02': Flag02,
  'flag-03': Flag03,
  'flag-04': Flag04,
  'flag-05': Flag05,
  'flag-06': Flag06,
  'flash-off': FlashOff,
  flash: Flash,
  'flex-align-bottom': FlexAlignBottom,
  'flex-align-left': FlexAlignLeft,
  'flex-align-right': FlexAlignRight,
  'flex-align-top': FlexAlignTop,
  'flip-backward': FlipBackward,
  'flip-forward': FlipForward,
  'folder-check': FolderCheck,
  'folder-closed': FolderClosed,
  'folder-code': FolderCode,
  'folder-download': FolderDownload,
  'folder-lock': FolderLock,
  'folder-minus': FolderMinus,
  'folder-plus': FolderPlus,
  'folder-question': FolderQuestion,
  'folder-search': FolderSearch,
  'folder-shield': FolderShield,
  'folder-x': FolderX,
  folder: Folder,
  framer: Framer,
  'gaming-pad-01': GamingPad01,
  'gaming-pad-02': GamingPad02,
  'gift-01': Gift01,
  'gift-02': Gift02,
  'git-branch-01': GitBranch01,
  'git-branch-02': GitBranch02,
  'git-commit': GitCommit,
  'git-merge': GitMerge,
  'git-pull-request': GitPullRequest,
  'glasses-01': Glasses01,
  'glasses-02': Glasses02,
  'globe-01': Globe01,
  'globe-02': Globe02,
  'globe-03': Globe03,
  'globe-04': Globe04,
  'globe-05': Globe05,
  'globe-06': Globe06,
  'google-chrome': GoogleChrome,
  'graduation-hat-01': GraduationHat01,
  'graduation-hat-02': GraduationHat02,
  'grid-01': Grid01,
  'grid-02': Grid02,
  'grid-03': Grid03,
  'grid-dots-blank': GridDotsBlank,
  'grid-dots-bottom': GridDotsBottom,
  'grid-dots-horizontal-center': GridDotsHorizontalCenter,
  'grid-dots-left': GridDotsLeft,
  'grid-dots-outer': GridDotsOuter,
  'grid-dots-right': GridDotsRight,
  'grid-dots-top': GridDotsTop,
  'grid-dots-vertical-center': GridDotsVerticalCenter,
  hand: Hand,
  'hard-drive': HardDrive,
  'hash-01': Hash01,
  'hash-02': Hash02,
  'heading-01': Heading01,
  'heading-02': Heading02,
  'heading-square': HeadingSquare,
  'headphones-01': Headphones01,
  'headphones-02': Headphones02,
  'heart-circle': HeartCircle,
  'heart-hand': HeartHand,
  'heart-hexagon': HeartHexagon,
  'heart-octagon': HeartOctagon,
  'heart-rounded': HeartRounded,
  'heart-square': HeartSquare,
  heart: Heart,
  hearts: Hearts,
  'help-circle': HelpCircle,
  'help-octagon-1': HelpOctagon1,
  'help-octagon': HelpOctagon,
  'help-square': HelpSquare,
  'hexagon-01': Hexagon01,
  'hexagon-02': Hexagon02,
  'home-01': Home01,
  'home-02': Home02,
  'home-03': Home03,
  'home-04': Home04,
  'home-05': Home05,
  'home-line': HomeLine,
  'home-smile': HomeSmile,
  'horizontal-bar-chart-01': HorizontalBarChart01,
  'horizontal-bar-chart-02': HorizontalBarChart02,
  'horizontal-bar-chart-03': HorizontalBarChart03,
  'hourglass-01': Hourglass01,
  'hourglass-02': Hourglass02,
  'hourglass-03': Hourglass03,
  'hurricane-01': Hurricane01,
  'hurricane-02': Hurricane02,
  'hurricane-03': Hurricane03,
  'image-01': Image01,
  'image-02': Image02,
  'image-03': Image03,
  'image-04': Image04,
  'image-05': Image05,
  'image-check': ImageCheck,
  'image-down': ImageDown,
  'image-indent-left': ImageIndentLeft,
  'image-indent-right': ImageIndentRight,
  'image-left': ImageLeft,
  'image-plus': ImagePlus,
  'image-right': ImageRight,
  'image-up': ImageUp,
  'image-user-check': ImageUserCheck,
  'image-user-down': ImageUserDown,
  'image-user-left': ImageUserLeft,
  'image-user-plus': ImageUserPlus,
  'image-user-right': ImageUserRight,
  'image-user-up': ImageUserUp,
  'image-user-x': ImageUserX,
  'image-user': ImageUser,
  'image-x': ImageX,
  'inbox-01': Inbox01,
  'inbox-02': Inbox02,
  infinity: Infinity,
  'info-circle': InfoCircle,
  'info-hexagon': InfoHexagon,
  'info-octagon': InfoOctagon,
  'info-square': InfoSquare,
  'intersect-circle': IntersectCircle,
  'intersect-square': IntersectSquare,
  'italic-01': Italic01,
  'italic-02': Italic02,
  'italic-square': ItalicSquare,
  'key-01': Key01,
  'key-02': Key02,
  'keyboard-01': Keyboard01,
  'keyboard-02': Keyboard02,
  'laptop-01': Laptop01,
  'laptop-02': Laptop02,
  'layer-single': LayerSingle,
  'layers-three-01': LayersThree01,
  'layers-three-02': LayersThree02,
  'layers-two-01': LayersTwo01,
  'layers-two-02': LayersTwo02,
  'layout-alt-01': LayoutAlt01,
  'layout-alt-02': LayoutAlt02,
  'layout-alt-03': LayoutAlt03,
  'layout-alt-04': LayoutAlt04,
  'layout-bottom': LayoutBottom,
  'layout-grid-01': LayoutGrid01,
  'layout-grid-02': LayoutGrid02,
  'layout-left': LayoutLeft,
  'layout-right': LayoutRight,
  'layout-top': LayoutTop,
  'left-indent-01': LeftIndent01,
  'left-indent-02': LeftIndent02,
  'letter-spacing-01': LetterSpacing01,
  'letter-spacing-02': LetterSpacing02,
  'life-buoy-01': LifeBuoy01,
  'life-buoy-02': LifeBuoy02,
  'lightbulb-01': Lightbulb01,
  'lightbulb-02': Lightbulb02,
  'lightbulb-03': Lightbulb03,
  'lightbulb-04': Lightbulb04,
  'lightbulb-05': Lightbulb05,
  'lightning-01': Lightning01,
  'lightning-02': Lightning02,
  'line-chart-down-01': LineChartDown01,
  'line-chart-down-02': LineChartDown02,
  'line-chart-down-03': LineChartDown03,
  'line-chart-down-04': LineChartDown04,
  'line-chart-down-05': LineChartDown05,
  'line-chart-up-01': LineChartUp01,
  'line-chart-up-02': LineChartUp02,
  'line-chart-up-03': LineChartUp03,
  'line-chart-up-04': LineChartUp04,
  'line-chart-up-05': LineChartUp05,
  'line-height': LineHeight,
  'link-01': Link01,
  'link-02': Link02,
  'link-03': Link03,
  'link-04': Link04,
  'link-05': Link05,
  'link-broken-01': LinkBroken01,
  'link-broken-02': LinkBroken02,
  'link-external-01': LinkExternal01,
  'link-external-02': LinkExternal02,
  list: List,
  'loading-01': Loading01,
  'loading-02': Loading02,
  'loading-03': Loading03,
  'lock-01': Lock01,
  'lock-02': Lock02,
  'lock-03': Lock03,
  'lock-04': Lock04,
  'lock-keyhole-circle': LockKeyholeCircle,
  'lock-keyhole-square': LockKeyholeSquare,
  'lock-unlocked-01': LockUnlocked01,
  'lock-unlocked-02': LockUnlocked02,
  'lock-unlocked-03': LockUnlocked03,
  'lock-unlocked-04': LockUnlocked04,
  'log-in-01': LogIn01,
  'log-in-02': LogIn02,
  'log-in-03': LogIn03,
  'log-in-04': LogIn04,
  'log-out-01': LogOut01,
  'log-out-02': LogOut02,
  'log-out-03': LogOut03,
  'log-out-04': LogOut04,
  'luggage-01': Luggage01,
  'luggage-02': Luggage02,
  'luggage-03': Luggage03,
  'magic-wand-01': MagicWand01,
  'magic-wand-02': MagicWand02,
  'mail-01': Mail01,
  'mail-02': Mail02,
  'mail-03': Mail03,
  'mail-04': Mail04,
  'mail-05': Mail05,
  'map-01': Map01,
  'map-02': Map02,
  mark: Mark,
  'marker-pin-01': MarkerPin01,
  'marker-pin-02': MarkerPin02,
  'marker-pin-03': MarkerPin03,
  'marker-pin-04': MarkerPin04,
  'marker-pin-05': MarkerPin05,
  'marker-pin-06': MarkerPin06,
  'maximize-01': Maximize01,
  'maximize-02': Maximize02,
  'medical-circle': MedicalCircle,
  'medical-cross': MedicalCross,
  'medical-square': MedicalSquare,
  'menu-01': Menu01,
  'menu-02': Menu02,
  'menu-03': Menu03,
  'menu-04': Menu04,
  'menu-05': Menu05,
  'message-alert-circle': MessageAlertCircle,
  'message-alert-square': MessageAlertSquare,
  'message-chat-circle': MessageChatCircle,
  'message-chat-square': MessageChatSquare,
  'message-check-circle': MessageCheckCircle,
  'message-check-square': MessageCheckSquare,
  'message-circle-01': MessageCircle01,
  'message-circle-02': MessageCircle02,
  'message-dots-circle': MessageDotsCircle,
  'message-dots-square': MessageDotsSquare,
  'message-heart-circle': MessageHeartCircle,
  'message-heart-square': MessageHeartSquare,
  'message-notification-circle': MessageNotificationCircle,
  'message-notification-square': MessageNotificationSquare,
  'message-plus-circle': MessagePlusCircle,
  'message-plus-square': MessagePlusSquare,
  'message-question-circle': MessageQuestionCircle,
  'message-question-square': MessageQuestionSquare,
  'message-smile-circle': MessageSmileCircle,
  'message-smile-square': MessageSmileSquare,
  'message-square-01': MessageSquare01,
  'message-square-02': MessageSquare02,
  'message-text-circle-01': MessageTextCircle01,
  'message-text-circle-02': MessageTextCircle02,
  'message-text-square-01': MessageTextSquare01,
  'message-text-square-02': MessageTextSquare02,
  'message-x-circle': MessageXCircle,
  'message-x-square': MessageXSquare,
  'microphone-01': Microphone01,
  'microphone-02': Microphone02,
  'microphone-off-01': MicrophoneOff01,
  'microphone-off-02': MicrophoneOff02,
  microscope: Microscope,
  'minimize-01': Minimize01,
  'minimize-02': Minimize02,
  'minus-circle': MinusCircle,
  'minus-square': MinusSquare,
  minus: Minus,
  'modem-01': Modem01,
  'modem-02': Modem02,
  'monitor-01': Monitor01,
  'monitor-02': Monitor02,
  'monitor-03': Monitor03,
  'monitor-04': Monitor04,
  'monitor-05': Monitor05,
  'moon-01': Moon01,
  'moon-02': Moon02,
  'moon-eclipse': MoonEclipse,
  'moon-star': MoonStar,
  mouse: Mouse,
  move: Move,
  'music-note-01': MusicNote01,
  'music-note-02': MusicNote02,
  'music-note-plus': MusicNotePlus,
  'navigation-pointer-01': NavigationPointer01,
  'navigation-pointer-02': NavigationPointer02,
  'navigation-pointer-off-01': NavigationPointerOff01,
  'navigation-pointer-off-02': NavigationPointerOff02,
  'notification-box': NotificationBox,
  'notification-message': NotificationMessage,
  'notification-text': NotificationText,
  octagon: Octagon,
  'package-check': PackageCheck,
  'package-minus': PackageMinus,
  'package-plus': PackagePlus,
  'package-search': PackageSearch,
  'package-x': PackageX,
  package: Package,
  'paint-pour': PaintPour,
  paint: Paint,
  palette: Palette,
  paperclip: Paperclip,
  'paragraph-spacing': ParagraphSpacing,
  'paragraph-wrap': ParagraphWrap,
  'passcode-lock': PasscodeLock,
  passcode: Passcode,
  passport: Passport,
  'pause-circle': PauseCircle,
  'pause-square': PauseSquare,
  'pen-tool-01': PenTool01,
  'pen-tool-02': PenTool02,
  'pen-tool-minus': PenToolMinus,
  'pen-tool-plus': PenToolPlus,
  'pencil-01': Pencil01,
  'pencil-02': Pencil02,
  'pencil-line': PencilLine,
  pentagon: Pentagon,
  'percent-01': Percent01,
  'percent-02': Percent02,
  'percent-03': Percent03,
  'perspective-01': Perspective01,
  'perspective-02': Perspective02,
  'phone-01': Phone01,
  'phone-02': Phone02,
  'phone-call-01': PhoneCall01,
  'phone-call-02': PhoneCall02,
  'phone-hang-up': PhoneHangUp,
  'phone-incoming-01': PhoneIncoming01,
  'phone-incoming-02': PhoneIncoming02,
  'phone-outgoing-01': PhoneOutgoing01,
  'phone-outgoing-02': PhoneOutgoing02,
  'phone-pause': PhonePause,
  'phone-plus': PhonePlus,
  'phone-x': PhoneX,
  phone: Phone,
  'pie-chart-01': PieChart01,
  'pie-chart-02': PieChart02,
  'pie-chart-03': PieChart03,
  'pie-chart-04': PieChart04,
  'piggy-bank-01': PiggyBank01,
  'piggy-bank-02': PiggyBank02,
  'pilcrow-01': Pilcrow01,
  'pilcrow-02': Pilcrow02,
  'pilcrow-square': PilcrowSquare,
  'pin-01': Pin01,
  'pin-02': Pin02,
  placeholder: Placeholder,
  plane: Plane,
  'play-circle': PlayCircle,
  'play-square': PlaySquare,
  play: Play,
  'plus-circle': PlusCircle,
  'plus-square': PlusSquare,
  plus: Plus,
  podcast: Podcast,
  'power-01': Power01,
  'power-02': Power02,
  'power-03': Power03,
  'presentation-chart-01': PresentationChart01,
  'presentation-chart-02': PresentationChart02,
  'presentation-chart-03': PresentationChart03,
  printer: Printer,
  'puzzle-piece-01': PuzzlePiece01,
  'puzzle-piece-02': PuzzlePiece02,
  'qr-code-01': QrCode01,
  'qr-code-02': QrCode02,
  'receipt-check': ReceiptCheck,
  receipt: Receipt,
  'recording-01': Recording01,
  'recording-02': Recording02,
  'recording-03': Recording03,
  'reflect-01': Reflect01,
  'reflect-02': Reflect02,
  'refresh-ccw-01': RefreshCcw01,
  'refresh-ccw-02': RefreshCcw02,
  'refresh-ccw-03': RefreshCcw03,
  'refresh-ccw-04': RefreshCcw04,
  'refresh-ccw-05': RefreshCcw05,
  'refresh-cw-01': RefreshCw01,
  'refresh-cw-02': RefreshCw02,
  'refresh-cw-03': RefreshCw03,
  'refresh-cw-04': RefreshCw04,
  'refresh-cw-05': RefreshCw05,
  'repeat-01': Repeat01,
  'repeat-02': Repeat02,
  'repeat-03': Repeat03,
  'repeat-04': Repeat04,
  'reverse-left': ReverseLeft,
  'reverse-right': ReverseRight,
  'right-indent-01': RightIndent01,
  'right-indent-02': RightIndent02,
  'rocket-01': Rocket01,
  'rocket-02': Rocket02,
  'roller-brush': RollerBrush,
  route: Route,
  'rows-01': Rows01,
  'rows-02': Rows02,
  'rows-03': Rows03,
  'rss-01': Rss01,
  'rss-02': Rss02,
  ruler: Ruler,
  safe: Safe,
  'sale-01': Sale01,
  'sale-02': Sale02,
  'sale-03': Sale03,
  'sale-04': Sale04,
  'save-01': Save01,
  'save-02': Save02,
  'save-03': Save03,
  'scale-01': Scale01,
  'scale-02': Scale02,
  'scale-03': Scale03,
  'scales-01': Scales01,
  'scales-02': Scales02,
  scan: Scan,
  'scissors-01': Scissors01,
  'scissors-02': Scissors02,
  'scissors-cut-01': ScissorsCut01,
  'scissors-cut-02': ScissorsCut02,
  'search-lg': SearchLg,
  'search-md': SearchMd,
  'search-refraction': SearchRefraction,
  'search-sm': SearchSm,
  'send-01': Send01,
  'send-02': Send02,
  'send-03': Send03,
  'server-01': Server01,
  'server-02': Server02,
  'server-03': Server03,
  'server-04': Server04,
  'server-05': Server05,
  'server-06': Server06,
  'settings-01': Settings01,
  'settings-02': Settings02,
  'settings-03': Settings03,
  'settings-04': Settings04,
  'share-01': Share01,
  'share-02': Share02,
  'share-03': Share03,
  'share-04': Share04,
  'share-05': Share05,
  'share-06': Share06,
  'share-07': Share07,
  'shield-01': Shield01,
  'shield-02': Shield02,
  'shield-03': Shield03,
  'shield-dollar': ShieldDollar,
  'shield-off': ShieldOff,
  'shield-plus': ShieldPlus,
  'shield-tick': ShieldTick,
  'shield-zap': ShieldZap,
  'shopping-bag-01': ShoppingBag01,
  'shopping-bag-02': ShoppingBag02,
  'shopping-bag-03': ShoppingBag03,
  'shopping-cart-01': ShoppingCart01,
  'shopping-cart-02': ShoppingCart02,
  'shopping-cart-03': ShoppingCart03,
  'shuffle-01': Shuffle01,
  'shuffle-02': Shuffle02,
  'signal-01': Signal01,
  'signal-02': Signal02,
  'signal-03': Signal03,
  simcard: Simcard,
  skew: Skew,
  'skip-back': SkipBack,
  'skip-forward': SkipForward,
  'slash-circle-01': SlashCircle01,
  'slash-circle-02': SlashCircle02,
  'slash-divider': SlashDivider,
  'slash-octagon': SlashOctagon,
  'sliders-01': Sliders01,
  'sliders-02': Sliders02,
  'sliders-03': Sliders03,
  'sliders-04': Sliders04,
  'snowflake-01': Snowflake01,
  'snowflake-02': Snowflake02,
  'spacing-height-01': SpacingHeight01,
  'spacing-height-02': SpacingHeight02,
  'spacing-width-01': SpacingWidth01,
  'spacing-width-02': SpacingWidth02,
  'speaker-01': Speaker01,
  'speaker-02': Speaker02,
  'speaker-03': Speaker03,
  'speedometer-01': Speedometer01,
  'speedometer-02': Speedometer02,
  'speedometer-03': Speedometer03,
  'speedometer-04': Speedometer04,
  square: Square,
  stand: Stand,
  'star-01': Star01,
  'star-02': Star02,
  'star-03': Star03,
  'star-04': Star04,
  'star-05': Star05,
  'star-06': Star06,
  'star-07': Star07,
  'stars-01': Stars01,
  'stars-02': Stars02,
  'stars-03': Stars03,
  'sticker-circle': StickerCircle,
  'sticker-square': StickerSquare,
  'stop-circle': StopCircle,
  'stop-square': StopSquare,
  stop: Stop,
  'strikethrough-01': Strikethrough01,
  'strikethrough-02': Strikethrough02,
  'strikethrough-square': StrikethroughSquare,
  subscript: Subscript,
  'sun-setting-01': SunSetting01,
  'sun-setting-02': SunSetting02,
  'sun-setting-03': SunSetting03,
  sun: Sun,
  sunrise: Sunrise,
  sunset: Sunset,
  'switch-horizontal-01': SwitchHorizontal01,
  'switch-horizontal-02': SwitchHorizontal02,
  'switch-vertical-01': SwitchVertical01,
  'switch-vertical-02': SwitchVertical02,
  table: Table,
  'tablet-01': Tablet01,
  'tablet-02': Tablet02,
  'tag-01': Tag01,
  'tag-02': Tag02,
  'tag-03': Tag03,
  'target-01': Target01,
  'target-02': Target02,
  'target-03': Target03,
  'target-04': Target04,
  'target-05': Target05,
  telescope: Telescope,
  'terminal-browser': TerminalBrowser,
  'terminal-circle': TerminalCircle,
  'terminal-square': TerminalSquare,
  terminal: Terminal,
  'text-input': TextInput,
  'thermometer-01': Thermometer01,
  'thermometer-02': Thermometer02,
  'thermometer-03': Thermometer03,
  'thermometer-cold': ThermometerCold,
  'thermometer-warm': ThermometerWarm,
  'thumbs-down': ThumbsDown,
  'thumbs-up': ThumbsUp,
  'ticket-01': Ticket01,
  'ticket-02': Ticket02,
  'toggle-01-left': Toggle01Left,
  'toggle-01-right': Toggle01Right,
  'toggle-02-left': Toggle02Left,
  'toggle-02-right': Toggle02Right,
  'toggle-03-left': Toggle03Left,
  'toggle-03-right': Toggle03Right,
  'tool-01': Tool01,
  'tool-02': Tool02,
  train: Train,
  tram: Tram,
  transform: Transform,
  'translate-01': Translate01,
  'translate-02': Translate02,
  'trash-01': Trash01,
  'trash-02': Trash02,
  'trash-03': Trash03,
  'trash-04': Trash04,
  'trend-down-01': TrendDown01,
  'trend-down-02': TrendDown02,
  'trend-up-01': TrendUp01,
  'trend-up-02': TrendUp02,
  triangle: Triangle,
  'trophy-01': Trophy01,
  'trophy-02': Trophy02,
  'truck-01': Truck01,
  'truck-02': Truck02,
  'tv-01': Tv01,
  'tv-02': Tv02,
  'tv-03': Tv03,
  'type-01': Type01,
  'type-02': Type02,
  'type-square': TypeSquare,
  'type-strikethrough-01': TypeStrikethrough01,
  'type-strikethrough-02': TypeStrikethrough02,
  'umbrella-01': Umbrella01,
  'umbrella-02': Umbrella02,
  'umbrella-03': Umbrella03,
  'underline-01': Underline01,
  'underline-02': Underline02,
  'underline-square': UnderlineSquare,
  'upload-01': Upload01,
  'upload-02': Upload02,
  'upload-03': Upload03,
  'upload-04': Upload04,
  'upload-cloud-01': UploadCloud01,
  'upload-cloud-02': UploadCloud02,
  'usb-flash-drive': UsbFlashDrive,
  'user-01': User01,
  'user-02': User02,
  'user-03': User03,
  'user-check-01': UserCheck01,
  'user-check-02': UserCheck02,
  'user-circle': UserCircle,
  'user-down-01': UserDown01,
  'user-down-02': UserDown02,
  'user-edit': UserEdit,
  'user-left-01': UserLeft01,
  'user-left-02': UserLeft02,
  'user-minus-01': UserMinus01,
  'user-minus-02': UserMinus02,
  'user-plus-01': UserPlus01,
  'user-plus-02': UserPlus02,
  'user-right-01': UserRight01,
  'user-right-02': UserRight02,
  'user-square': UserSquare,
  'user-up-01': UserUp01,
  'user-up-02': UserUp02,
  'user-x-01': UserX01,
  'user-x-02': UserX02,
  'users-01': Users01,
  'users-02': Users02,
  'users-03': Users03,
  'users-check': UsersCheck,
  'users-down': UsersDown,
  'users-edit': UsersEdit,
  'users-left': UsersLeft,
  'users-minus': UsersMinus,
  'users-plus': UsersPlus,
  'users-right': UsersRight,
  'users-up': UsersUp,
  'users-x': UsersX,
  variable: Variable,
  'video-recorder-off': VideoRecorderOff,
  'video-recorder': VideoRecorder,
  virus: Virus,
  voicemail: Voicemail,
  'volume-max': VolumeMax,
  'volume-min': VolumeMin,
  'volume-minus': VolumeMinus,
  'volume-plus': VolumePlus,
  'volume-x': VolumeX,
  'wallet-01': Wallet01,
  'wallet-02': Wallet02,
  'wallet-03': Wallet03,
  'wallet-04': Wallet04,
  'wallet-05': Wallet05,
  'watch-circle': WatchCircle,
  'watch-square': WatchSquare,
  waves: Waves,
  'webcam-01': Webcam01,
  'webcam-02': Webcam02,
  'wifi-off': WifiOff,
  wifi: Wifi,
  'wind-01': Wind01,
  'wind-02': Wind02,
  'wind-03': Wind03,
  'x-circle': XCircle,
  'x-close': XClose,
  'x-square': XSquare,
  x: X,
  youtube: Youtube,
  'zap-circle': ZapCircle,
  'zap-fast': ZapFast,
  'zap-off': ZapOff,
  'zap-square': ZapSquare,
  zap: Zap,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
};
